/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_xcleans_image_ImageWrapp */
#ifndef _Included_com_xcleans_image_ImageWrapp
#define _Included_com_xcleans_image_ImageWrapp

#define ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))
/**
 * Explicitly marks result of an expression as unused.
 * We instruct the compiler to be very strict when it comes to code
 * like unused arguments that could indicate a bug. Because of that, handling
 * intentionally unused arguments requires tricks like casting to void. This
 * macro provides a readable name for this operation.
 */
#define UNUSED(expr) ((void) (expr));
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, "image2", __VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xcleans_image_ImageWrapp
 * Method:    handlerImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;DII)V
 */
//JNIEXPORT void JNICALL Java_com_xcleans_image_ImageWrapp_handlerImage
//  (JNIEnv *, jobject, jstring, jstring, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
